spring:
  application:
    name: zuul-server
server:
  port: 8790
  servlet:
    context-path: /cloud
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8787/eureka}

# http"//localhost:5555/cloud[/endpoint/]
zuul:
  routes:
    product: /product/**
    feign-client: /feign-client/**
#    statistic-chain-client: /statistic/**
#    secured-feign-client: /feign/**
  sensitiveHeaders: Cookie, Set-Cookie
# ribbon:
#   ReadTimeout: 60000
