server:
  port: 8788
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  application:
    name: product
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8787/eureka}